# University Database - SQL Practice
### Introductory Level Questions

In [1]:
!pip install pandasql
import pandas as pd
import pandasql as psql

Course     = pd.read_excel("https://github.com/ogut77/University/blob/main/Course.xlsx?raw=true")
Faculty    = pd.read_excel("https://github.com/ogut77/University/blob/main/Faculty.xlsx?raw=true")
Student    = pd.read_excel("https://github.com/ogut77/University/blob/main/Student.xlsx?raw=true")
Enrollment = pd.read_excel("https://github.com/ogut77/University/blob/main/Enrollment.xlsx?raw=true")
Offering   = pd.read_excel("https://github.com/ogut77/University/blob/main/Offering.xlsx?raw=true")
Faculty_1  = pd.read_excel("https://github.com/ogut77/University/blob/main/Faculty_1.xlsx?raw=true")

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.49)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2026.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=24d31343d7464a2346e0b22146a2df230c6183cf8e0fab296ffdd8a4f6ae0903
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

## Database Schema

| Table | Key Columns |
|---|---|
| **Student** | StdNo, StdFirstName, StdLastName, StdCity, StdMajor, StdClass, StdGPA |
| **Offering** | OfferNo, CourseNo, OffTerm, OffYear, OffLocation, FacNo |
| **Enrollment** | OfferNo, StdNo, EnrGrade |
| **Faculty** | FacNo, FacFirstName, FacLastName, FacDept, FacRank, FacSalary |
| **Course** | CourseNo, CrsDesc, CrsUnits |

---
# Part 1: Multiple Table Questions

In [2]:
#Q1- List the first name, last name of all students and the grade they received in each enrollment.

txt='''

'''
Q1 = psql.sqldf(txt)
Q1

   StdFirstName StdLastName  EnrGrade
0         HOMER       WELLS       2.0
1         HOMER       WELLS       3.2
2         HOMER       WELLS       3.2
3         HOMER       WELLS       3.3
4         HOMER       WELLS       3.5
5           BOB     NORBERT       2.7
6           BOB     NORBERT       3.2
7           BOB     NORBERT       3.5
8           BOB     NORBERT       3.7
9         CANDY     KENDALL       2.8
10        CANDY     KENDALL       3.1
11        CANDY     KENDALL       3.2
12        CANDY     KENDALL       3.5
13        WALLY     KENDALL       3.2
14        WALLY     KENDALL       3.2
15        WALLY     KENDALL       3.3
16          JOE     ESTRADA       3.1
17          JOE     ESTRADA       3.4
18          JOE     ESTRADA       3.4
19       MARIAH       DODGE       2.6
20       MARIAH       DODGE       2.6
21       MARIAH       DODGE       3.6
22       MARIAH       DODGE       3.8
23         TESS       DODGE       3.3
24         TESS       DODGE       3.3
25         TESS       DODGE       3.4
26      ROBERTO     MORALES       3.5
27      ROBERTO     MORALES       3.8
28   CRISTOPHER       COLAN       3.1
29   CRISTOPHER       COLAN       3.4
30         LUKE      BRAZZI       2.9
31         LUKE      BRAZZI       3.4
32         LUKE      BRAZZI       3.7
33      WILLIAM     PILGRIM       3.1
34      WILLIAM     PILGRIM       3.1
35      WILLIAM     PILGRIM       3.4
36      WILLIAM     PILGRIM       4.0

In [3]:
#Q2- Show all offering numbers along with the first and last name of the faculty teaching them.

txt='''

'''
Q2 = psql.sqldf(txt)
Q2

    OfferNo FacFirstName FacLastName
0      1234      LEONARD       VINCE
1      3333      LEONARD       VINCE
2      4321      LEONARD       VINCE
3      4444     VICTORIA    EMMANUEL
4      5555        NICKI       MACON
5      5678        JULIA       MILLS
6      5679   CRISTOPHER       COLAN
7      6666        JULIA       MILLS
8      7777        NICKI       MACON
9      8888      LEONARD       FIBON
10     9876      LEONARD       FIBON

In [4]:
#Q3- List student first name, last name and the course number they are enrolled in.

txt='''

'''
Q3 = psql.sqldf(txt)
Q3

   StdFirstName StdLastName CourseNo
0         HOMER       WELLS    IS320
1         HOMER       WELLS    IS320
2         HOMER       WELLS   FIN300
3         HOMER       WELLS    IS480
4         HOMER       WELLS    IS480
5           BOB     NORBERT    IS320
6           BOB     NORBERT   FIN300
7           BOB     NORBERT    IS480
8           BOB     NORBERT    IS460
9         CANDY     KENDALL    IS320
10        CANDY     KENDALL    IS480
11        CANDY     KENDALL   FIN450
12        CANDY     KENDALL    IS460
13        WALLY     KENDALL    IS320
14        WALLY     KENDALL    IS480
15        WALLY     KENDALL    IS460
16          JOE     ESTRADA    IS320
17          JOE     ESTRADA    IS480
18          JOE     ESTRADA    IS460
19       MARIAH       DODGE    IS320
20       MARIAH       DODGE    IS480
21       MARIAH       DODGE   FIN450
22       MARIAH       DODGE    IS460
23         TESS       DODGE    IS320
24         TESS       DODGE    IS480
25         TESS       DODGE    IS460
26      ROBERTO     MORALES    IS320
27      ROBERTO     MORALES    IS480
28   CRISTOPHER       COLAN    IS320
29   CRISTOPHER       COLAN   FIN480
30         LUKE      BRAZZI    IS320
31         LUKE      BRAZZI    IS480
32         LUKE      BRAZZI   FIN480
33      WILLIAM     PILGRIM    IS320
34      WILLIAM     PILGRIM    IS480
35      WILLIAM     PILGRIM   FIN480
36      WILLIAM     PILGRIM    IS460

In [5]:
#Q4- Show the course description and the term it is offered in.

txt='''

'''
Q4 = psql.sqldf(txt)
Q4

                                 CrsDesc OffTerm  OffYear
0                FUNDAMENTALS OF FINANCE  WINTER     2017
1              PRINCIPLES OF INVESTMENTS  WINTER     2017
2                      CORPORATE FINANCE  SPRING     2017
3   FUNDAMENTALS OF BUSINESS PROGRAMMING    FALL     2016
4   FUNDAMENTALS OF BUSINESS PROGRAMMING    FALL     2016
5   FUNDAMENTALS OF BUSINESS PROGRAMMING  SPRING     2017
6   FUNDAMENTALS OF BUSINESS PROGRAMMING  SUMMER     2017
7   FUNDAMENTALS OF BUSINESS PROGRAMMING  SUMMER     2017
8   FUNDAMENTALS OF BUSINESS PROGRAMMING  WINTER     2017
9                       SYSTEMS ANALYSIS  SPRING     2017
10                      SYSTEMS ANALYSIS  SUMMER     2016
11   FUNDAMENTALS OF DATABASE MANAGEMENT  SPRING     2017
12   FUNDAMENTALS OF DATABASE MANAGEMENT  WINTER     2017

In [6]:
#Q5- List all students enrolled in course IS320 along with their grade.

txt='''

'''
Q5 = psql.sqldf(txt)
Q5

   StdFirstName StdLastName  EnrGrade
0         HOMER       WELLS       3.3
1         CANDY     KENDALL       3.5
2         WALLY     KENDALL       3.2
3           JOE     ESTRADA       3.1
4        MARIAH       DODGE       3.8
5          TESS       DODGE       3.4
6         HOMER       WELLS       3.5
7           BOB     NORBERT       3.2
8       ROBERTO     MORALES       3.5
9    CRISTOPHER       COLAN       3.1
10         LUKE      BRAZZI       3.4
11      WILLIAM     PILGRIM       3.1

In [7]:
#Q6- Show faculty first name, last name and the course description of what they teach.

txt='''

'''
Q6 = psql.sqldf(txt)
Q6

   FacFirstName FacLastName                               CrsDesc
0       LEONARD       VINCE  FUNDAMENTALS OF BUSINESS PROGRAMMING
1       LEONARD       VINCE  FUNDAMENTALS OF BUSINESS PROGRAMMING
2       LEONARD       VINCE  FUNDAMENTALS OF BUSINESS PROGRAMMING
3      VICTORIA    EMMANUEL  FUNDAMENTALS OF BUSINESS PROGRAMMING
4       LEONARD       FIBON  FUNDAMENTALS OF BUSINESS PROGRAMMING
5       LEONARD       FIBON                      SYSTEMS ANALYSIS
6         NICKI       MACON               FUNDAMENTALS OF FINANCE
7         NICKI       MACON                     CORPORATE FINANCE
8    CRISTOPHER       COLAN   FUNDAMENTALS OF DATABASE MANAGEMENT
9         JULIA       MILLS             PRINCIPLES OF INVESTMENTS
10        JULIA       MILLS   FUNDAMENTALS OF DATABASE MANAGEMENT

In [8]:
#Q7- List all offerings held in FALL 2016 with the student names enrolled in them.

txt='''

'''
Q7 = psql.sqldf(txt)
Q7

    OfferNo StdFirstName StdLastName
0      1234        HOMER       WELLS
1      1234        CANDY     KENDALL
2      1234        WALLY     KENDALL
3      1234          JOE     ESTRADA
4      1234       MARIAH       DODGE
5      1234         TESS       DODGE
6      4321        HOMER       WELLS
7      4321          BOB     NORBERT
8      4321      ROBERTO     MORALES
9      4321   CRISTOPHER       COLAN
10     4321         LUKE      BRAZZI
11     4321      WILLIAM     PILGRIM

In [9]:
#Q8- Show each course description and how many students are enrolled in it.

txt='''

'''
Q8 = psql.sqldf(txt)
Q8

                                CrsDesc  NumStudents
0                     CORPORATE FINANCE            3
1  FUNDAMENTALS OF BUSINESS PROGRAMMING           12
2   FUNDAMENTALS OF DATABASE MANAGEMENT           11
3               FUNDAMENTALS OF FINANCE            2
4             PRINCIPLES OF INVESTMENTS            2
5                      SYSTEMS ANALYSIS            7

In [10]:
#Q9- List the student name, course number and grade for all SEATTLE students.

txt='''

'''
Q9 = psql.sqldf(txt)
Q9

   StdFirstName StdLastName CourseNo  EnrGrade
0         HOMER       WELLS    IS320       3.3
1         HOMER       WELLS    IS320       3.5
2         HOMER       WELLS   FIN300       3.2
3         HOMER       WELLS    IS480       3.2
4         HOMER       WELLS    IS480       2.0
5         WALLY     KENDALL    IS320       3.2
6         WALLY     KENDALL    IS480       3.3
7         WALLY     KENDALL    IS460       3.2
8           JOE     ESTRADA    IS320       3.1
9           JOE     ESTRADA    IS480       3.4
10          JOE     ESTRADA    IS460       3.4
11       MARIAH       DODGE    IS320       3.8
12       MARIAH       DODGE    IS480       2.6
13       MARIAH       DODGE   FIN450       3.6
14       MARIAH       DODGE    IS460       2.6
15      ROBERTO     MORALES    IS320       3.5
16      ROBERTO     MORALES    IS480       3.8
17   CRISTOPHER       COLAN    IS320       3.1
18   CRISTOPHER       COLAN   FIN480       3.4
19         LUKE      BRAZZI    IS320       3.4
20         LUKE      BRAZZI    IS480       2.9
21         LUKE      BRAZZI   FIN480       3.7

In [11]:
#Q10- Show each faculty member name, their department and the course number they teach.

txt='''

'''
Q10 = psql.sqldf(txt)
Q10

   FacFirstName FacLastName FacDept CourseNo
0    CRISTOPHER       COLAN      MS    IS480
1      VICTORIA    EMMANUEL      MS    IS320
2       LEONARD       FIBON      MS    IS320
3       LEONARD       FIBON      MS    IS460
4         NICKI       MACON     FIN   FIN300
5         NICKI       MACON     FIN   FIN480
6         JULIA       MILLS     FIN   FIN450
7         JULIA       MILLS     FIN    IS480
8       LEONARD       VINCE      MS    IS320
9       LEONARD       VINCE      MS    IS320
10      LEONARD       VINCE      MS    IS320

---
# Part 2: Subquery Questions

In [12]:
#Q11- Find all students whose GPA is higher than the average GPA of all students.

txt='''

'''
Q11 = psql.sqldf(txt)
Q11

  StdFirstName StdLastName  StdGPA
0        CANDY     KENDALL     3.5
1          JOE     ESTRADA     3.2
2       MARIAH       DODGE     3.6
3         TESS       DODGE     3.3
4   CRISTOPHER       COLAN     4.0
5      WILLIAM     PILGRIM     3.8

In [13]:
#Q12- List all faculty members who earn more than the average faculty salary.

txt='''

'''
Q12 = psql.sqldf(txt)
Q12

  FacFirstName FacLastName  FacSalary
0     VICTORIA    EMMANUEL     120000
1      LEONARD       FIBON      70000
2        JULIA       MILLS      75000

In [14]:
#Q13- Find all students who are not enrolled in any course.

txt='''

'''
Q13 = psql.sqldf(txt)
Q13

Empty DataFrame
Columns: [StdFirstName, StdLastName]
Index: []

In [15]:
#Q14- List all courses that have never been offered.

txt='''

'''
Q14 = psql.sqldf(txt)
Q14

  CourseNo                       CrsDesc
0    IS470  BUSINESS DATA COMMUNICATIONS

In [16]:
#Q15- Find the student with the highest GPA in the IS major.

txt='''

'''
Q15 = psql.sqldf(txt)
Q15

  StdFirstName StdLastName  StdGPA
0   CRISTOPHER       COLAN     4.0